### ISSUE TITLE
usepopcorn css problem 

### ISSUE THREAD

**Issue by Amarnath1904** [jonasschmedtmann/ultimate-react-course#75]
I am seeing scrollbars on the usepopcorn project 

![image](https://github.com/jonasschmedtmann/ultimate-react-course/assets/51597733/7f139600-7b6c-45ef-925e-12bffea4cc11)

**Comment by Amarnath1904** [comment]
solved it by 
```css

.box {
/*css*/
-ms-overflow-style: none;
  scrollbar-width: none; 
}
``` 
and 

```css
.list{
/*css*/
-ms-overflow-style: none;
  scrollbar-width: none; 
}
```
